language: python
dist: xenial

os:
  - linux

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libopenblas-dev
      - libopenblas-base

env:
  global:
    - CIBW_SKIP="*-win32 *-manylinux_i686 cp27-*"
    # - TWINE_USERNAME=__token__

jobs:
  include:
    # perform a linux build
    - services: docker
      install: pip install cibuildwheel==1.1.0
      script: cibuildwheel --output-dir wheelhouse
    # and a mac build
    - os: osx
      language: shell
      install: pip install cibuildwheel==1.1.0
      script: cibuildwheel --output-dir wheelhouse
    # and a windows build
    - os: windows
      language: shell
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.0

install:
  - python3 -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse
  - python3 setup.py sdist --formats=gztar

notifications:
    email: false

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python3 -m twine upload wheelhouse/*.whl dist/*.tar.gz; fi
